-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        blur = {
            enabled = true,
        },
    },
    general = {
        gaps_out = 10,
    },
    misc = {
        disable_splash_rendering = false,
    },
})

-- Monitors
hl.monitor({
    output = "DP-3",
    disabled = false,
    mode = "1920x1080@165.00Hz",
    position = "0x0",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "HDMI-A-1",
    disabled = false,
    mode = "1920x1080@74.97Hz",
    position = "1920x-55",
    scale = 1,
    cm = "srgb",
})
