background_opacity 0.9
window_padding_width 10
map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard

font_family Cousine Nerd Font

# BEGIN_KITTY_THEME
# T-Money
include current-theme.conf
# END_KITTY_THEME